import { ProductCondition } from "@feri/database";

export type DemoCatalogProduct = {
  imagePath: string;
  title: string;
  description: string;
  priceRupees: number;
  condition: ProductCondition;
  categorySlug: string;
  brand?: string;
};

const { NEW, LIKE_NEW, GOOD, FAIR } = ProductCondition;

export const DEMO_CATALOG_PRODUCTS: readonly DemoCatalogProduct[] = [
  {
    imagePath: "clothes/blue-designer-jacket-man",
    title: "Blue designer jacket, men",
    description: "Structured blue jacket with a clean designer cut. Lined and ready to wear.",
    priceRupees: 3200,
    condition: LIKE_NEW,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/blue-half-zipup-sweater",
    title: "Blue half zip-up sweater",
    description: "Soft knit sweater with a half zip collar. Warm for Kathmandu winters.",
    priceRupees: 1100,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/blue-jeans-with-embroidery",
    title: "Blue jeans with embroidery",
    description: "Straight blue jeans with hand-style embroidery down the legs.",
    priceRupees: 1600,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/brown-tshirt-with-white-boardersman",
    title: "Brown t-shirt with white border",
    description: "Brown cotton t-shirt with contrast white edging on the sleeves and collar.",
    priceRupees: 450,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/brown-cotrise-baggy-pant",
    title: "Brown baggy pants, low rise",
    description: "Relaxed brown pants with a low rise and a wide leg.",
    priceRupees: 950,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/brown-pant-with-middle-blue-flower-embroidery",
    title: "Brown pants with blue flower embroidery",
    description: "Brown pants with a blue flower embroidered down the middle of each leg.",
    priceRupees: 1300,
    condition: LIKE_NEW,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/brown-top-pancho-style",
    title: "Brown poncho-style top",
    description: "Loose brown top cut like a poncho. Easy to layer.",
    priceRupees: 800,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/brown-woman-belly-pants",
    title: "Brown belly pants, women",
    description: "Brown high-waist pants with a flattering fit at the belly.",
    priceRupees: 1000,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/dirty-jeans-with-embroidery",
    title: "Washed jeans with embroidery",
    description: "Faded wash jeans with embroidery details. The worn look is the style.",
    priceRupees: 1500,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/flared-jeans-designer",
    title: "Designer flared jeans",
    description: "Flared jeans with a fitted thigh and a wide hem.",
    priceRupees: 1900,
    condition: LIKE_NEW,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/flared-jeans-with-lace",
    title: "Flared jeans with lace",
    description: "Flared jeans with lace panels at the hem.",
    priceRupees: 1750,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/formal-short-and-red-waist-coat-female",
    title: "Formal shorts with red waistcoat, women",
    description: "Matching formal shorts and red waistcoat set for office or events.",
    priceRupees: 2400,
    condition: LIKE_NEW,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/furr-coat",
    title: "Faux fur coat",
    description: "Thick fur-style coat, very warm. Worn a few times.",
    priceRupees: 3800,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/leather-jacket",
    title: "Leather jacket",
    description: "Classic leather jacket with a zip front. Broken in and comfortable.",
    priceRupees: 4500,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/orange-flared-body-hugging-tshirt",
    title: "Orange flared fitted t-shirt",
    description: "Body-hugging orange t-shirt with flared sleeves.",
    priceRupees: 600,
    condition: LIKE_NEW,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/orange-striped-sweater",
    title: "Orange striped sweater",
    description: "Cozy knit sweater with orange stripes.",
    priceRupees: 1200,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/red-hald-sleeve-bow-top",
    title: "Red half-sleeve bow top",
    description: "Red top with half sleeves and a bow detail at the front.",
    priceRupees: 700,
    condition: LIKE_NEW,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/alladin-shirt-with-waist-coat",
    title: "Aladdin-style shirt with waistcoat",
    description: "Flowing shirt paired with a waistcoat. Great for festivals and parties.",
    priceRupees: 2100,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/baggy-pants-1",
    title: "Baggy pants",
    description: "Wide, relaxed pants that are comfortable all day.",
    priceRupees: 900,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/check-pant",
    title: "Check pants",
    description: "Checked pants with a straight leg. Easy to dress up or down.",
    priceRupees: 1000,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/cowboy-pants",
    title: "Cowboy pants",
    description: "Western-style pants with a bootcut leg.",
    priceRupees: 1150,
    condition: FAIR,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/jeans-coat",
    title: "Denim coat",
    description: "Long denim coat with button front. Works over anything.",
    priceRupees: 2600,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/jeans-fur-jacket",
    title: "Denim jacket with fur collar",
    description: "Denim jacket lined with soft fur at the collar and cuffs.",
    priceRupees: 2900,
    condition: LIKE_NEW,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/leather-jacket-man",
    title: "Leather jacket, men",
    description: "Men's leather jacket with a slim fit and zip pockets.",
    priceRupees: 4800,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/mini-skirt",
    title: "Mini skirt",
    description: "Short skirt that goes with boots or sneakers.",
    priceRupees: 650,
    condition: GOOD,
    categorySlug: "clothes",
  },
  {
    imagePath: "clothes/pj-pants",
    title: "Pyjama pants",
    description: "Soft pyjama pants for lounging at home. Washed and clean.",
    priceRupees: 500,
    condition: GOOD,
    categorySlug: "clothes",
  },

  {
    imagePath: "shoes/chuck-70s-brown",
    title: "Chuck 70s sneakers, brown",
    description: "High-top canvas sneakers in brown with the classic cushioned sole.",
    priceRupees: 5200,
    condition: GOOD,
    categorySlug: "shoes",
    brand: "Converse",
  },
  {
    imagePath: "shoes/lacy-brown-heels",
    title: "Lacy brown heels",
    description: "Brown heels with lace detail. Comfortable for an evening out.",
    priceRupees: 1800,
    condition: LIKE_NEW,
    categorySlug: "shoes",
  },
  {
    imagePath: "shoes/loafers",
    title: "Loafers",
    description: "Slip-on loafers that suit both formal and casual outfits.",
    priceRupees: 2200,
    condition: GOOD,
    categorySlug: "shoes",
  },
  {
    imagePath: "shoes/nb-shoes",
    title: "NB running shoes",
    description: "Cushioned everyday running shoes with a light upper.",
    priceRupees: 4200,
    condition: GOOD,
    categorySlug: "shoes",
  },
  {
    imagePath: "shoes/ankle-shoes",
    title: "Ankle boots",
    description: "Ankle-height boots with a low block heel.",
    priceRupees: 2600,
    condition: GOOD,
    categorySlug: "shoes",
  },
  {
    imagePath: "shoes/ballet-flats",
    title: "Ballet flats",
    description: "Flat shoes with a soft sole, easy for long days on your feet.",
    priceRupees: 1200,
    condition: LIKE_NEW,
    categorySlug: "shoes",
  },
  {
    imagePath: "shoes/boots-long",
    title: "Long boots",
    description: "Knee-high boots that stay up well. Good for winter.",
    priceRupees: 3600,
    condition: GOOD,
    categorySlug: "shoes",
  },
  {
    imagePath: "shoes/cherry-shoes",
    title: "Cherry red shoes",
    description: "Bright cherry red shoes that stand out with simple outfits.",
    priceRupees: 1500,
    condition: GOOD,
    categorySlug: "shoes",
  },
  {
    imagePath: "shoes/pointed-boot",
    title: "Pointed boots",
    description: "Boots with a pointed toe and a clean silhouette.",
    priceRupees: 3000,
    condition: GOOD,
    categorySlug: "shoes",
  },
  {
    imagePath: "shoes/puma-shoes-blue",
    title: "Puma shoes, blue",
    description: "Blue Puma sneakers with a comfortable sole.",
    priceRupees: 3400,
    condition: GOOD,
    categorySlug: "shoes",
    brand: "Puma",
  },
  {
    imagePath: "shoes/puma",
    title: "Puma sneakers",
    description: "Classic Puma sneakers for everyday wear.",
    priceRupees: 3300,
    condition: GOOD,
    categorySlug: "shoes",
    brand: "Puma",
  },
  {
    imagePath: "shoes/read-loafers",
    title: "Red loafers",
    description: "Red slip-on loafers that add colour to a plain outfit.",
    priceRupees: 2000,
    condition: GOOD,
    categorySlug: "shoes",
  },
  {
    imagePath: "shoes/zara-heels-dark-brown",
    title: "Zara heels, dark brown",
    description: "Dark brown heels with a neat finish.",
    priceRupees: 2300,
    condition: LIKE_NEW,
    categorySlug: "shoes",
    brand: "Zara",
  },

  {
    imagePath: "watches/digital-watch",
    title: "Digital watch",
    description: "Digital watch with a clear display. Battery tested.",
    priceRupees: 1900,
    condition: GOOD,
    categorySlug: "watches",
  },
  {
    imagePath: "watches/beads-watch-multicolour",
    title: "Multicolour beaded watch",
    description: "Watch with a colourful beaded strap and a small round face.",
    priceRupees: 1400,
    condition: LIKE_NEW,
    categorySlug: "watches",
  },
  {
    imagePath: "watches/black-band-watches",
    title: "Black band watch",
    description: "Simple watch on a black band that goes with everything.",
    priceRupees: 2100,
    condition: GOOD,
    categorySlug: "watches",
  },
  {
    imagePath: "watches/brown-band-watch",
    title: "Brown band watch",
    description: "Watch on a brown band, tested and keeping time.",
    priceRupees: 2400,
    condition: GOOD,
    categorySlug: "watches",
  },
  {
    imagePath: "watches/casio-watch",
    title: "Casio watch",
    description: "Casio watch that runs well. Small marks from daily use.",
    priceRupees: 2800,
    condition: GOOD,
    categorySlug: "watches",
    brand: "Casio",
  },
  {
    imagePath: "watches/oval-leo-print-watch",
    title: "Oval leopard print watch",
    description: "Oval watch with a leopard print strap.",
    priceRupees: 1700,
    condition: LIKE_NEW,
    categorySlug: "watches",
  },
  {
    imagePath: "watches/pocket-watch-vintage",
    title: "Vintage pocket watch",
    description: "Old-style pocket watch with a chain. A nice piece for collectors.",
    priceRupees: 5500,
    condition: FAIR,
    categorySlug: "watches",
  },
  {
    imagePath: "watches/silver-watch",
    title: "Silver watch",
    description: "Silver-tone watch with a slim case.",
    priceRupees: 3000,
    condition: GOOD,
    categorySlug: "watches",
  },
  {
    imagePath: "watches/vintage-watch-leather",
    title: "Vintage watch, leather strap",
    description: "Vintage-style watch on a leather strap with a worn-in look.",
    priceRupees: 3600,
    condition: FAIR,
    categorySlug: "watches",
  },

  {
    imagePath: "tech/folding-phone",
    title: "Folding phone",
    description: "Foldable phone that works well. Screen and hinge checked.",
    priceRupees: 38000,
    condition: GOOD,
    categorySlug: "tech",
  },
  {
    imagePath: "tech/ipad",
    title: "iPad",
    description: "iPad in working order with a clear screen. Charger included.",
    priceRupees: 24000,
    condition: GOOD,
    categorySlug: "tech",
    brand: "Apple",
  },
  {
    imagePath: "tech/kindle",
    title: "Kindle e-reader",
    description: "E-reader with a sharp screen and a battery that lasts for weeks.",
    priceRupees: 8500,
    condition: GOOD,
    categorySlug: "tech",
    brand: "Kindle",
  },
  {
    imagePath: "tech/nokia-keypad-phone",
    title: "Nokia keypad phone",
    description: "Classic keypad phone with long battery life. Great as a backup phone.",
    priceRupees: 2500,
    condition: GOOD,
    categorySlug: "tech",
    brand: "Nokia",
  },
  {
    imagePath: "tech/sony-silver-camera",
    title: "Sony silver camera",
    description: "Compact silver Sony camera. Takes sharp everyday photos.",
    priceRupees: 12000,
    condition: GOOD,
    categorySlug: "tech",
    brand: "Sony",
  },
  {
    imagePath: "tech/video-cam",
    title: "Video camera",
    description: "Handheld video camera for home movies and vlogs.",
    priceRupees: 9500,
    condition: FAIR,
    categorySlug: "tech",
  },
  {
    imagePath: "tech/canon-digicam",
    title: "Canon digital camera",
    description: "Point-and-shoot Canon camera with that early-2000s photo look.",
    priceRupees: 11000,
    condition: GOOD,
    categorySlug: "tech",
    brand: "Canon",
  },
  {
    imagePath: "tech/fuzifilm-xt30",
    title: "Fujifilm X-T30 camera",
    description: "Mirrorless Fujifilm X-T30 camera body in working condition.",
    priceRupees: 62000,
    condition: LIKE_NEW,
    categorySlug: "tech",
    brand: "Fujifilm",
  },
  {
    imagePath: "tech/headphone",
    title: "Headphones",
    description: "Over-ear headphones with clear sound. Cushions in good shape.",
    priceRupees: 2800,
    condition: GOOD,
    categorySlug: "tech",
  },
  {
    imagePath: "tech/ipod",
    title: "iPod",
    description: "Music player in working order. Comes with a charging cable.",
    priceRupees: 6500,
    condition: FAIR,
    categorySlug: "tech",
    brand: "Apple",
  },

  {
    imagePath: "others/miumiu-bag",
    title: "Miu Miu leather handbag",
    description: "Dark brown leather handbag with gold hardware and side ties.",
    priceRupees: 28000,
    condition: GOOD,
    categorySlug: "bags",
    brand: "Miu Miu",
  },
  {
    imagePath: "others/red-bag",
    title: "Red bag",
    description: "Bright red bag with room for daily essentials.",
    priceRupees: 2200,
    condition: GOOD,
    categorySlug: "bags",
  },
  {
    imagePath: "others/vint-wallet",
    title: "Brown leather wallet",
    description: "Compact brown leather wallet with a gold logo and a folding flap.",
    priceRupees: 3500,
    condition: LIKE_NEW,
    categorySlug: "bags",
  },

  {
    imagePath: "others/crystal-oval-ring",
    title: "Crystal oval ring",
    description: "Ring with an oval crystal stone. Sparkles in the light.",
    priceRupees: 700,
    condition: NEW,
    categorySlug: "other",
  },
  {
    imagePath: "others/black-opium-perfume",
    title: "Black Opium perfume",
    description: "Black Opium perfume bottle with most of the scent left.",
    priceRupees: 5500,
    condition: GOOD,
    categorySlug: "other",
    brand: "Yves Saint Laurent",
  },
  {
    imagePath: "others/blue-de-chanel",
    title: "Bleu de Chanel perfume",
    description: "Bleu de Chanel bottle, mostly full.",
    priceRupees: 8500,
    condition: GOOD,
    categorySlug: "other",
    brand: "Chanel",
  },
  {
    imagePath: "others/cap-leather",
    title: "Leather cap",
    description: "Leather cap with a soft finish and a good fit.",
    priceRupees: 900,
    condition: GOOD,
    categorySlug: "other",
  },
  {
    imagePath: "others/cowboy-hat",
    title: "Cowboy hat",
    description: "Wide-brim cowboy hat. Holds its shape well.",
    priceRupees: 1500,
    condition: GOOD,
    categorySlug: "other",
  },
  {
    imagePath: "others/dior-hypnotic-poison",
    title: "Dior Hypnotic Poison perfume",
    description: "Hypnotic Poison perfume bottle with a warm, sweet scent.",
    priceRupees: 6500,
    condition: GOOD,
    categorySlug: "other",
    brand: "Dior",
  },
  {
    imagePath: "others/hair-beads",
    title: "Hair beads",
    description: "Set of decorative hair beads for braids and ponytails.",
    priceRupees: 300,
    condition: NEW,
    categorySlug: "other",
  },
  {
    imagePath: "others/hanky-red",
    title: "Red handkerchief",
    description: "Red cotton handkerchief that doubles as a neck scarf.",
    priceRupees: 250,
    condition: LIKE_NEW,
    categorySlug: "other",
  },
  {
    imagePath: "others/oval-glasses",
    title: "Oval glasses",
    description: "Oval frame glasses with a light, thin frame.",
    priceRupees: 800,
    condition: GOOD,
    categorySlug: "other",
  },
  {
    imagePath: "others/perfumes",
    title: "Perfume set",
    description: "A small set of perfume bottles, sold together.",
    priceRupees: 4500,
    condition: GOOD,
    categorySlug: "other",
  },
  {
    imagePath: "others/princess-necklace",
    title: "Princess necklace",
    description: "Delicate necklace with a princess-style pendant.",
    priceRupees: 650,
    condition: LIKE_NEW,
    categorySlug: "other",
  },
  {
    imagePath: "others/rhode-lipbalm",
    title: "Rhode lip balm",
    description: "Rhode lip balm, lightly used.",
    priceRupees: 1100,
    condition: GOOD,
    categorySlug: "other",
    brand: "Rhode",
  },
  {
    imagePath: "others/silver-hairpins",
    title: "Silver hairpins",
    description: "Set of silver-tone hairpins for updos and buns.",
    priceRupees: 400,
    condition: NEW,
    categorySlug: "other",
  },
  {
    imagePath: "others/sol-de-jenerio-perfume",
    title: "Sol de Janeiro perfume",
    description: "Sol de Janeiro body mist with a warm, sweet scent.",
    priceRupees: 3800,
    condition: GOOD,
    categorySlug: "other",
    brand: "Sol de Janeiro",
  },
  {
    imagePath: "others/sun-necklace",
    title: "Sun necklace",
    description: "Necklace with a small sun pendant on a fine chain.",
    priceRupees: 600,
    condition: LIKE_NEW,
    categorySlug: "other",
  },
  {
    imagePath: "others/vintage-brown-suage",
    title: "Brown studded belt",
    description: "Wide brown belt with metal studs and an oval buckle.",
    priceRupees: 1300,
    condition: GOOD,
    categorySlug: "other",
  },
];
